### ISSUE TITLE
無法辨識原神視窗

### ISSUE THREAD

**Issue by soondro2266** [myHuTao-qwq/HutaoFisher#12]
HWND hWnd = FindHandle("YuanShen.exe");
at src/screenshot.cpp line 23
其他區(例如我)的視窗handle可能是GenshinImpact.exe
就會有無法抓取視窗的問題
Fisher: Fatal screenshot error: the game handle is NULL! The fisher has automatically stopped.
請問該如何修改後編譯成exe檔?
![image](https://github.com/user-attachments/assets/92874d85-a9b8-4796-9b7c-be64eb6dfe56)

**Comment by myHuTao-qwq** [comment]
最新的release里面应该解决了这个问题, 直接下载试试能不能用吧.

**Comment by soondro2266** [comment]
可以使用，但是release裡寫的是GenshinInpact.exe，應改正為GenshinImpact.exe

**Comment by soondro2266** [comment]
不過拋竿的時候從來都偵測不到拋竿成功。
Error occured while fishing: checkBite: the float doesn't splash within acceptable time!
魚竿成功拋出並落水，不過卻偵測不到，導致後續上鉤部分都無法實現。
其他部分都正常，拋竿位置也正確，想請問原神內部畫面設定有甚麼特別要注意的嗎?

**Comment by myHuTao-qwq** [comment]
草草草 太久不玩原神已经连原神都不会写了orz
画面要求长宽比为16:9, 分辨率理论上要高于1024*576, 作者在1080p和2k的环境测试过没问题, 其他的设置不知道有什么影响作者也没修改过应该保持默认即可. 方便上传一下log/images文件夹里面的报错图片吗? 文件名里面带err的图片

**Comment by soondro2266** [comment]
![1730260422_err_bbox](https://github.com/user-attachments/assets/d9f63e8a-e0af-44ee-9b2d-96c9acaa5403)

這圖片應該是沒什麼幫助，因為拋竿位置確實正確且也能吸引到魚，但是程式檢測不到拋竿成功，停留在等待拋竿的階段，所以截圖應該也是timeout後才截圖的。請問一下程式檢測拋竿成功與否的依據是什麼，我之後可以自己截圖後上傳。

**Comment by myHuTao-qwq** [comment]
检测的代码是src/fishing.cpp中的void Fisher::checkBite()函数, 第714到725行的while循环. 程序在循环中截图并缩放到标准大小, 检测一个预先给定的区域canny处理后的图像与模板(resource/imgs/hook.png)的PSNR. 如果PSNR小于阈值则认为抛竿成功退出循环. 超时则抛竿失败.

**Comment by myHuTao-qwq** [comment]
![381385065-d9f63e8a-e0af-44ee-9b2d-96c9acaa5403](https://github.com/user-attachments/assets/8cf020f1-d2c5-4425-b12a-bdd407f25222)
我发现问题了. 你的图片中鱼钩图标的位置与我这里用于确定鱼钩图标位置的图片中鱼钩的位置明显不一样, 因此程序取的地方位置不对. 我不清楚这是什么原因导致的. 如果是米哈游在新版本的原神中挪动了鱼钩图标的位置, 只需要修改第720行中预先写入的区域. 但是如果图标的位置现在会在不同人/次的钓鱼中变化, 那就需要把这一步换成模板匹配来适应位置的移动.
很遗憾我现在没时间修复这个问题.

**Comment by soondro2266** [comment]
研究了一下github release的用法，以我的情況來說，fishing.cpp 裡 line 720 & 747 鎖定圖標位置是(850, 508) ，我改成 (839, 508)後可以正常運作，謝謝作者!

**Comment by myHuTao-qwq** [comment]
能解决问题就好, 不谢:)
