### ISSUE TITLE
大佬问一下第二个参数为关的情况下不会自动钓鱼

### ISSUE THREAD

**Issue by lie5860** [myHuTao-qwq/HutaoFisher#3]
我使用000 100都无法钓鱼 一定要第二个参数为1的时候 钓鱼的过程中才会帮忙把浮标移动到张力区。这是为啥嘞。

**Comment by myHuTao-qwq** [comment]
我刚刚在自己的电脑测试了一下没有碰到这个问题, 能把你电脑的配置和钓鱼场所钓鱼环境之类的发一下吗.....
我认为可能很有用的参数: 显示器分辨率, 钓鱼点的位置, 出问题时游戏的时间(这体现光照等因素), 是否使用鱼线稳定器等等

**Comment by Lzsh1** [comment]
大佬适配了须弥的鱼群了吗

**Comment by lie5860** [comment]
> 大佬适配了须弥的鱼群了吗

大佬太强了 我已经把地图上所有鱼池都钓了一圈 都能钓呢

**Comment by lie5860** [comment]
> 我刚刚在自己的电脑测试了一下没有碰到这个问题, 能把你电脑的配置和钓鱼场所钓鱼环境之类的发一下吗..... 我认为可能很有用的参数: 显示器分辨率, 钓鱼点的位置, 出问题时游戏的时间(这体现光照等因素), 是否使用鱼线稳定器等等

不是很清楚。。因为鱼用010配置都钓完了。~感谢大佬的程序降低了使用门槛（之前py的太难装了。小白的我依赖装了半天。。。）。抓的过程中遇到几个小问题。
1. 失败次数是否可以支持配置。现在是失败n次后会自动结束。像我可能一个池子挂那10分钟 他自己怎么钓 钓完了就行。。希望失败次数可以自己配多一些。。。
2. 钓鱼过程中 可能存在 鱼咬钩的时间慢了1、2秒。这时候刚好鼠标收杆，刚好收杆和鱼咬钩冲突了。。导致收杆失败。。然后咬钩后的没有走识别和进入张力区的操作，就导致鱼跑掉了。而且一般这个过程会一直报失败。导致流程中断了。。。整个钓下来的过程中。这个几率还是有一点的。10%这样吧。

**Comment by myHuTao-qwq** [comment]
1日后再说吧, 开学了忙的要死orz 或者有别人有能力也可以改一下, 应该不难, 加个配置文件之类的orz
2应该是只有假龙有这个问题吧? 那个是因为我希望抛竿以后鱼马上过来咬钩, 但是又不知道怎么判断鱼是否有来咬钩, 所以最大等待时间就卡在我见过的有来咬钩的最长的等待时间多一会..... 我试的时候应该除了假龙以外都问题不大, 假龙单纯就是抛竿判断有问题, 毕竟假龙的体型和运动都比较复杂....

**Comment by lie5860** [comment]
> 1日后再说吧, 开学了忙的要死orz 或者有别人有能力也可以改一下, 应该不难, 加个配置文件之类的orz 2应该是只有假龙有这个问题吧? 那个是因为我希望抛竿以后鱼马上过来咬钩, 但是又不知道怎么判断鱼是否有来咬钩, 所以最大等待时间就卡在我见过的有来咬钩的最长的等待时间多一会..... 我试的时候应该除了假龙以外都问题不大, 假龙单纯就是抛竿判断有问题, 毕竟假龙的体型和运动都比较复杂....

好的嘞。话说2的问题有办法通过识别力量条出现后 进入自动钓鱼的流程吗。。（只是随口说说，可能和设计不符，先感谢大佬了~

**Comment by myHuTao-qwq** [comment]
这单纯就是某种洁癖而已, 我不希望抛竿歪掉以后还在瞎等....虽然效果目前不是很好orz 现在是识别钓鱼按钮(右下角), 基本和力度条同步出现, 换成力度条不会有本质区别.
