### ISSUE TITLE
HDR下好像不能用

### ISSUE THREAD

**Issue by WongHohin** [myHuTao-qwq/HutaoFisher#5]
如题，开启了WIN11的自动HDR之后好像会在选择鱼饵的界面卡住，鼠标粘在确认键上，还是说3.2更新了FSR2的问题

**Comment by myHuTao-qwq** [comment]
我电脑没升win11, 这段时间也没空, 有空的时候我看看吧, 不过卡住的意思是后面的步骤直接不运行了吗? 还是鼠标点不下去? 程序有提示吗?

**Comment by WongHohin** [comment]
在选择鱼饵的界面没按确认，然后就开始寻找目标了。在log里面看了截图，就是hdr的问题，开了hdr后普通的截图会泛白，你随便开个支持hdr的游戏然后用微信或者qq截个图就能看出来区别

**Comment by myHuTao-qwq** [comment]
我看了一下, 我的显示器不支持hdr = = 估计是修不了了
