### ISSUE TITLE
反馈两个小问题

### ISSUE THREAD

**Issue by NeptuneTop** [myHuTao-qwq/HutaoFisher#6]
首先吹一波，傻瓜式的全自动钓鱼是个好软件，上手简单无门槛便于推广（可惜现在钓鱼的需求量太小了）
然后反馈一下使用过程中遇到的两个小问题，不清楚其他人是否有遇到：
1、钓鱼时力点在最佳张力区右边时（比如最佳张力区突然往左快速移动后就会出现这种情况）力点向左回移到最佳张力区右端时也会触发点击导致力点一直处在最佳张力区右边。
![image](https://user-images.githubusercontent.com/123738938/215084384-24883e30-31b3-4ff9-aa3a-ab5131b244a9.png)
2、在抛竿后如果鱼儿不咬钩（太近了吓跑或者抛竿的时候正在移动而游走）过几秒钟后会自动收竿，然后就一直不会继续钓鱼，即使手动开启命令（有开启提示音）也不会继续运行，需要重新启动软件才能正常运行
![image](https://user-images.githubusercontent.com/123738938/215084764-0231f2fe-c962-4917-af2d-6e0cf6fbec73.png)

**Comment by NeptuneTop** [comment]
2的话原来是要输入错误中止原因才能继续运行，是我不认真了哈哈，1的话只遇到1次不知道是不是我的问题，以及21：9屏幕要改设置改半天才能用上有点心酸

**Comment by myHuTao-qwq** [comment]
1是因为图像匹配的阈值好像没有很好的确定方法(至少就我的水平来说orz)所以在光标重叠的时候可能会出现左边框右边框匹配错误的情况, 能发一下出现bug的地点吗? 虽然可能没时间修了....... 怕不是清籁岛阴间光环境的问题........可能要把图像匹配的部分改一改吧orz

**Comment by myHuTao-qwq** [comment]
1是因为图像匹配的阈值好像没有很好的确定方法(至少就我的水平来说orz)所以在光标重叠的时候可能会出现左边框右边框匹配错误的情况, 能发一下出现bug的地点吗? 虽然可能没时间修了....... 怕不是清籁岛阴间光环境的问题........可能要把图像匹配的部分改一改吧orz

**Comment by myHuTao-qwq** [comment]
话说改21:9这么好改的吗......如果是这样希望您把改完的代码开源一下, 或许日后要做不同分辨率的适配会方便一些, 也可以方便其他想改自己分辨率的原友?

**Comment by NeptuneTop** [comment]
1的话在明亮和阴暗环境都有概率出现。21：9是改自己电脑的分辨率设置啦，不知道为什么不重启电脑重启软件也会当我是21：9比例所以弄了好久都没成功。我试过21：9的屏幕运行，搜索鱼和抛饵没问题，换饵选择没错但是点确定会点错，推测不匹配的原因应该是取了相对值移动鼠标点击的操作，收竿操作也有问题，直接识别不到，我C++是五年前学的现在也不做开发已经没有读代码能力了）可以试试通过读取原神的窗口句柄来获取分辨率和定位？

**Comment by myHuTao-qwq** [comment]
啊好吧我研究一下(问题不大我只上过非计算机专业的编程入门课orz)

**Comment by myHuTao-qwq** [comment]
把模板匹配的部分改进了一下, 1应该已经几乎不会发生了orz
