### ISSUE TITLE
[feature request] 当鱼未上钩的时候，自动重试

### ISSUE THREAD

**Issue by leon-can-write** [myHuTao-qwq/HutaoFisher#9]
钓鱼的时候偶尔会出现鱼不上钩的情况:

```
enter fail reason: 0-succeed, 1-too close, 2-too far, other-don't save
```
需要人工介入。

通常这个是因为鱼突然转向或者正好游远了。这是暂时的问题，一般重试一下就能解决问题。所以我在想能不能自动重试 3 次，如果失败了再给这个prompt让人工介入

**Comment by VEmpYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近有事，几天后回复。请原谅。

**Comment by myHuTao-qwq** [comment]
这个中断是我自动设置的希望用户可以帮忙采集数据的功能, 不过现在看来不应该对这个功能抱有太大期望……如果你觉得这个不方便, 打开config.json, 将里面的”logData”一项从true改成false, 这样咬钩失败的时候应该就不会让用户输入失败原因了, 从而钓鱼器可以自动重试

**Comment by myHuTao-qwq** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。   您好，我最近有事，几天后回复。请原谅。

???
